services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=your_master_key_here
    depends_on:
      - db
      - redis
      - sidekiq

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: PASSWORD7412

  redis:
    image: redis:6.2

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis

volumes:
  postgres_data: